import { Disc3 } from "lucide-react";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="p-4">
          <div className="flex items-center gap-2">
            <Disc3 className="w-6 h-6 animate-spin" />
            <h1 className="text-xl font-bold text-foreground italic">
              AutoForm
            </h1>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
